### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `codespell -L crate .`

### CODE REVIEW

**Comment by jam1garner** [comment]
would you mind rebasing this? If not I'll take care of the merge conflicts when I'm less busy

**Comment by kianmeng** [comment]
@jam1garner Done.

**Comment by jam1garner** [comment]
thank you ❤️❤️❤️

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
